name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Bot
      run: docker build . --file Dockerfile --tag database
    - name: Run Bot
      env:
        TOKEN: ${{ secrets.TOKEN }}
      run: docker run -e TOKEN=${TOKEN} database
